---
# REM: maunally install before using with
# $ ansible-galaxy install -r requirements.yml

- src: https://github.com/dheles/ansible-role-login-user
  name: login-user

- src: https://github.com/dheles/ansible-role-secure-ssh
  name: secure-ssh

- src: https://github.com/dheles/ansible-role-java.git
  name: java

- src: https://github.com/dheles/deploy-keys-ansible-role
  version: v1.0.0
  name: deploy-keys

- src: https://github.com/geerlingguy/ansible-role-repo-epel.git
  version: 1.2.3
  name: repo-epel

- src: https://github.com/geerlingguy/ansible-role-pip.git
  version: 1.3.0
  name: pip

- src: https://github.com/geerlingguy/ansible-role-docker.git
  version: 2.5.2
  name: docker

- src: https://github.com/dheles/postgres-ansible-role
  name: postgres

- src: https://github.com/dheles/firewalld-ansible-role
  name: firewalld

- src: https://github.com/farooqsadiq/ansible-role-ius-repo.git
  name: repo-ius

- src: https://github.com/geerlingguy/ansible-role-git.git
  version: 2.0.4
  name: git

- src: https://github.com/geerlingguy/ansible-role-nginx.git
  version: 2.6.2
  name: nginx
