ui_patron:
  hostname: "databases-{{ environ }}.{{ domainname}}"
  root:     '/opt/ui_patron'
  index:    'index.html'

ui_staff:
  hostname:  "{{ hostname }}.{{ domainname }}"
  root:      '/opt/ui_staff'
  index:     'index.html'

lara:
  hostname: "lara-{{ environ }}.{{ domainname}}"

ssl_self_sign_cert:              false
ssl_provided_cert:               true
ssl_certificate_file:            'star_library.jhu.edu.crt'
ssl_certificate_interm_file:     'star_library.jhu.edu_interm.crt'
ssl_certificate_dhparam_file:    'dhparam.pem'
ssl_certificate_key_file:        'star_library.jhu.edu.key'
ssl_certificate_cert_path:       '/etc/pki/tls/certs'
ssl_certificate_key_path:        '/etc/pki/tls/private'

nginx_vhost_template:   'local_nginx_vhost.conf.j2'

nginx_vhosts:
  - server_name: 'localhost'
    listen:      '80 default_server'
    filename:    'default.conf'
    return:      '301 https://$host$request_uri'
    template:    "{{ nginx_vhost_template }}"
    state: 'present'
  - server_name: "{{ ui_patron.hostname }}"
    listen:      '443 ssl http2'
    extra_parameters: |
      location / {
         root {{ui_patron.root}};
         try_files $uri $uri/ /{{ ui_patron.index }};
      }
    filename: "{{ ui_patron.hostname }}.conf"
    template: "{{ nginx_vhost_template }}"
    state: "present"
  - server_name: "{{ ui_staff.hostname }}"
    listen: '443 ssl http2'
    extra_parameters: |
      location / {
         root {{ui_staff.root}};
         try_files $uri $uri/ /{{ ui_patron.index }};
      }
      location /_/invoke/tenant/diku/saml/ {
        proxy_pass http://127.0.0.1:9130/_/invoke/tenant/diku/saml/;
        proxy_set_header X-Okapi-Tenant diku;
      }
    filename: "{{ ui_staff.hostname }}.conf"
    template:    "{{ nginx_vhost_template }}"
    state: 'present'
  - server_name: "{{ lara.hostname }}"
    listen: '443 ssl http2'
    extra_parameters: |
      location / {
          proxy_pass http://127.0.0.1:{{ okapi_port }};
          proxy_set_header X-Okapi-Tenant diku;
      }
    filename: "{{ lara.hostname }}.conf"
    template:    "{{ nginx_vhost_template }}"
    state: 'present'
