---
# setup vars
environ:  "dev" # dev || test || stage || preprod || prod

# private vars
login_user_passphrase:  "{{ vault_login_user_passphrase }}"

# ssh vars
create_login_user:      true

# apache vars:
hostname:               "{{ app_name }}-{{environ}}"
domainname:             "library.jhu.edu"

docker_etc_hosts:
  "oriole-dev.library.jhu.edu": "{{ ansible_default_ipv4.address }}"

# On dev open okapi port for use with data load
# We do not have a self signed cert
firewalld_ports:
  - port: "{{ okapi_port }}"
    protocol: tcp
    state: enabled

# SSH vars
login_password:         "{{ lookup('ini', 'login_password section=dev file=~/.ansible.ini') }}"
login_user_grant_sudo:  true
