---
# setup vars
environ:  "dev" # dev || test || stage || preprod || prod

# private vars
login_user_passphrase:  "{{ vault_login_user_passphrase }}"

# apache vars:
hostname:               "{{ app_name }}-{{environ}}"
domainname:             "library.jhu.edu"

docker_etc_hosts:
  "oriole-dev.library.jhu.edu": "{{ ansible_default_ipv4.address }}"
