---
# Set okapi envs
- hosts: oriole

  tasks:
    
    - name: test envs
      uri:
        url: "{{external_okapi_url}}/_/env/{{ item.key }}"
        status_code: [200,404]
      register: check_okapi_envs
      loop: "{{ lookup('dict', okapi_envs) }}"

    - name: set envs
      uri:
        url: "{{external_okapi_url}}/_/env"
        method: 'POST'
        body:
          name: "{{ item.item.key }}"
          value: "{{ item.item.value}}"
        body_format: 'json'
        status_code: [200,201]
      loop: "{{ check_okapi_envs.results|selectattr('status', 'equalto',400) | list }}"
