- name: install oriole prereqs
  hosts: okapi

  pre_tasks:
    - import_tasks: 'tasks/ssl.yml'

  roles:
    - { role: nginx,     tags: ['nginx'],    become: true }

  tasks:
    - name: create ui-patron root
      become: true
      file:
        path: "{{ ui_patron.root }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        state: directory
        mode: 0755
      register: ui_patron_dir
      notify: restart nginx

    - name: create ui-patron index file
      become: true
      copy:
        dest: "{{ ui_patron.root }}/{{ ui_patron.index }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        content: |
          <h1>Patron UI<h1>
      when: ui_patron_dir.changed

    - name: create ui-staff root
      become: true
      file:
        path: "{{ ui_staff.root }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        state: directory
        mode: 0755
      register: ui_staff_dir
      notify: restart nginx

    - name: create ui-staff index file
      become: true
      copy:
        dest: "{{ ui_staff.root }}/{{ ui_staff.index }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        content: |
          <h1>Staff UI<h1>
      when: ui_staff_dir.changed
